import { useRef, useState } from "react";
import { Bell, Building2, Download, Moon, Palette, RotateCcw, Save, ShieldCheck, Upload, UserRound } from "lucide-react";

export default function Settings({ settings, setSettings, darkMode, onThemeToggle, onExportBackup, onImportBackup, onResetDemo, toast }) {
  const [form, setForm] = useState(settings);
  const fileRef = useRef(null);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => { setSettings(form); toast("Settings saved successfully."); };
  const handleFile = (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => onImportBackup(String(reader.result));
    reader.readAsText(file);
    event.target.value = "";
  };
  return <div className="page-stack settings-page">
    <div className="page-heading-row"><div><span className="section-kicker">Workspace</span><h1>Settings</h1><p>Configure company details, preferences, alerts, appearance and local data backups.</p></div><button className="button primary" onClick={save}><Save size={16} /> Save settings</button></div>
    <section className="settings-grid">
      <article className="content-card settings-card wide"><div className="settings-card-head"><span className="settings-icon indigo"><Building2 size={20} /></span><div><h2>Company profile</h2><p>Used across reports, exports and workspace identity.</p></div></div><div className="form-grid two"><label className="field"><span>Company name</span><input value={form.companyName} onChange={(e) => update("companyName", e.target.value)} /></label><label className="field"><span>Business email</span><input type="email" value={form.companyEmail} onChange={(e) => update("companyEmail", e.target.value)} /></label><label className="field"><span>Phone</span><input value={form.phone} onChange={(e) => update("phone", e.target.value)} /></label><label className="field"><span>Currency</span><select value={form.currency} onChange={(e) => update("currency", e.target.value)}><option value="INR">INR — Indian Rupee</option><option value="USD">USD — US Dollar</option><option value="AED">AED — UAE Dirham</option><option value="SAR">SAR — Saudi Riyal</option></select></label><label className="field"><span>Default tax rate (%)</span><input type="number" min="0" max="100" value={form.taxRate} onChange={(e) => update("taxRate", Number(e.target.value))} /></label><label className="field"><span>Global low stock threshold</span><input type="number" min="0" value={form.lowStockThreshold} onChange={(e) => update("lowStockThreshold", Number(e.target.value))} /></label></div></article>
      <article className="content-card settings-card"><div className="settings-card-head"><span className="settings-icon cyan"><UserRound size={20} /></span><div><h2>Admin profile</h2><p>Your workspace display information.</p></div></div><div className="profile-settings-block"><div className="large-avatar">MA</div><label className="field"><span>Display name</span><input value={form.profileName} onChange={(e) => update("profileName", e.target.value)} /></label><label className="field"><span>Role</span><input value={form.profileRole} onChange={(e) => update("profileRole", e.target.value)} /></label></div></article>
      <article className="content-card settings-card"><div className="settings-card-head"><span className="settings-icon amber"><Bell size={20} /></span><div><h2>Notifications</h2><p>Choose how alerts behave.</p></div></div><div className="settings-toggle-list"><label className="settings-toggle"><div><strong>In-app notifications</strong><span>Low stock, out of stock and order alerts</span></div><input type="checkbox" checked={form.notifications} onChange={(e) => update("notifications", e.target.checked)} /><i /></label><label className="settings-toggle"><div><strong>Email alerts</strong><span>Demo preference for future backend integration</span></div><input type="checkbox" checked={form.emailAlerts} onChange={(e) => update("emailAlerts", e.target.checked)} /><i /></label></div></article>
      <article className="content-card settings-card"><div className="settings-card-head"><span className="settings-icon violet"><Palette size={20} /></span><div><h2>Appearance</h2><p>Customize the interface experience.</p></div></div><div className="appearance-options"><button className={`appearance-choice ${!darkMode ? "active" : ""}`} onClick={() => darkMode && onThemeToggle()}><span className="appearance-preview light"><i /><i /><i /></span><strong>Light</strong></button><button className={`appearance-choice ${darkMode ? "active" : ""}`} onClick={() => !darkMode && onThemeToggle()}><span className="appearance-preview dark"><i /><i /><i /></span><strong><Moon size={14} /> Dark</strong></button></div><label className="settings-toggle compact-toggle"><div><strong>Compact density</strong><span>Reduce table and card spacing</span></div><input type="checkbox" checked={form.compactMode} onChange={(e) => update("compactMode", e.target.checked)} /><i /></label></article>
      <article className="content-card settings-card"><div className="settings-card-head"><span className="settings-icon emerald"><ShieldCheck size={20} /></span><div><h2>Data & backup</h2><p>Your data is stored in this browser.</p></div></div><div className="backup-actions"><button className="button secondary full-width" onClick={onExportBackup}><Download size={16} /> Export complete backup</button><button className="button secondary full-width" onClick={() => fileRef.current?.click()}><Upload size={16} /> Import backup</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={handleFile} /><button className="button danger subtle full-width" onClick={onResetDemo}><RotateCcw size={16} /> Reset demo data</button></div><div className="security-note"><ShieldCheck size={17} /><span><strong>Local-first demo</strong> No server or external database is used in this beginner version.</span></div></article>
    </section>
  </div>;
}
